name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Git
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github

      - name: Run release script
        shell: pwsh
        run: ./release.ps1
