name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Run release script
        shell: pwsh
        run: ./release.ps1
